### PR TITLE
Feat/topnbar icon

### PR DESCRIPTION
**Pull request by jopedroliveira**
#120 
 Added Station logo as menu bar icon, setup and app icon

### CODE REVIEW

**Review by juliangruber — APPROVED** [review]
The large tray icons have become significantly smaller, we can adjust this later on though. Thank you @jopedroliveira!

**Comment by jopedroliveira** [comment]
Windows setup sidebar is missing.

**Comment by jopedroliveira** [comment]
Windows setup sidebar is missing.

**Review by bajtos — APPROVED** [review]
Awesome 👏🏻 

Could you please check why the `git` history contains commits from `main` that are not related to your changes?

**Comment by bajtos** [comment]
> Could you please check why the `git` history contains commits from `main` that are not related to your changes?

GitHub should be showing only the following two commits in this pull request:
- e1af3df8fdca76d3700d6ebe6c5ba5833b46ffad
- 5fab10feadb3e5d75e3869b763373daf2e314f59

Can you try to run the following commands to fix?

Step 1 - make sure your `main` branch is in sync with our main:

```
git checkout main
git pull upstream # the name of the remote for this repo
git reset --hard upstream/main
git push --force-with-lease --force-if-includes
```

Step 2 - rewrite your git history to start from the latest main:

```
git checkout feat/topnbar-icon
git rebase main
git push --force-with-lease --force-if-includes
```

**Pull request merged**
